/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.azienda.com.app;

public abstract class Employee implements Payable{
    private String name;

    public Employee(String name) {
        this.name=name;
    }

    public String getName() {
        return name;
    }
}