/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.azienda.com.app;

import java.util.*;

public class HRDepartment <T extends Employee>{
    private List<T> employees = new ArrayList<>();

    public void addEmployee(T employee) {
        employees.add(employee);
    }

    public double totalSalaries() {
        double total = 0.0;
        for (T emp : employees) {
            total += emp.getSalary();
        }
        return total;
    }

    public void printEmployeeNames() {
        for (T emp : employees) {
            System.out.println(emp.getName());
        }
    }
}
